### ISSUE TITLE
window环境functions.php 181行file_get_contents

### ISSUE THREAD

**Issue by ghosthgytop** [zhufenghua1998/bp3#12]
window环境
{"errmsg":"http request error!"}
Array
(
    [type] => 2
    [message] => file_get_contents(http://pan.baidu.com/rest/2.0/xpan/multimedia?access_token=xxxxxxxxxxxx&method=filemetas&fsids=[2.8257792358967E 14]&dlink=1&thumb=1&dlink=1&extra=1): failed to open stream: HTTP request failed! HTTP/1.1 400 Bad Request

    [file] => D:\phpstudy_pro\WWW\bp3-main\functions.php
    [line] => 181
)
{"msg":"The following is the HTTP request header information!"}
Array
(
    [http] => Array
        (
            [method] => GET
            [header] => Array
                (
                    [0] => User-Agent:pan.baidu.com
                )

            [content] => 
        )

    [ssl] => Array
        (
            [verify_peer] => 
            [verify_peer_name] => 
        )

)
{"msg":"The following is the HTTP response header information!"}
Array
(
    [0] => HTTP/1.1 400 Bad Request
)

**Comment by zhufenghua1998** [comment]
windows可能有bug是目录分隔符，从您这描述，像是token失效。遇到问题可先尝试升级最新版本（或许已经修复），并重新授权。如您无法解决，我们可以提供免费的远程技术支持，感谢您的反馈。

**Comment by ghosthgytop** [comment]
windows可能有各种奇怪的bug，我想改用linux里面的docker安装，请问有docker直接安装的镜像吗。

**Comment by ghosthgytop** [comment]
bp3文件从windows电脑复制到CentOS 7.9.2009 x86_64系统功能一切正常
