### ISSUE TITLE
能否支持断点续传

### ISSUE THREAD

**Issue by mogumc** [zhufenghua1998/bp3#14]
试着自己写第二条线程没有文件(
如果大佬可以解决的话希望能够提供多线程+断点续传下载方案

**Comment by zhufenghua1998** [comment]
感谢关注，已提供多线程+断点续传，请更新版本或在官方demo体验，推荐4线程，线程过多可能触发频控或受服务器性能影响造成减速。

**Comment by filecxx** [comment]
> 感谢关注，已提供多线程+断点续传，请更新版本或在官方demo体验，推荐4线程，线程过多可能触发频控或受服务器性能影响造成减速。

可以考虑创建文件蜈蚣链接，支持限制用户下载时候使用的连接数量
http://www.filecxx.com/zh_CN/documentation/create_address.html

例子
`
create_filec_address({uri:"http://....",max_connections:4});
`

**Comment by mogumc** [comment]
感谢
