### ISSUE TITLE
[bug]无法修改config内容,更改/inc/fun_core.php解决

### ISSUE THREAD

**Issue by Xiefengshang** [zhufenghua1998/bp3#15]
RT,只能手动更改目录下的`config.php`文件,网页上保存设置无反应。报错内容如下
```
<br />
<b>Warning</b>:  file_put_contents(/www/wwwroot/网页目录../config.php): failed to open stream: No such file or directory in <b>/www/wwwroot/网页目录/inc/fun_core.php</b> on line <b>402</b><br />
{"errno": 0, "errmsg": "success"}
```
看报错发现是`config.php`目录获取错误，根目录多了个`.`的样子？于是去查。  
查看了`fun_core.php`的402行文件,删掉`get_base_root().`即可保存,难道是相对目录和绝对目录弄错了？  
不知道是否只有我的环境遇到这个问题，麻烦开发者了。  
因为没啥时间没仔细看到底是不是这个问题(，所以不确定是不是我环境的问题。  
update:  
按照上述操作之后可以在页面中保存设置并应用，但无法进行百度授权认证(指登录完成之后授权信息无法写入)，更改回原版之后即可完成授权认证。

**Comment by zhufenghua1998** [comment]
感谢反馈，我记得已经修改过了，后来撤销了推送，导致代码丢失了，小bug无需担心，本项目会长期维护。至于本次反馈的问题，不应该修改fun_core，而是应该写为save_config()，也就是无需参数，会自动正确保存config，而无需手动指定相对位置。


在下个版本更新前，我会把所有功能点全部列出来，每次更新后全部功能点都进行测试，尽可能减少此类情况。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhufenghua1998/bp3"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 晚上8:52
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[zhufenghua1998/bp3] [bug]无法修改config内容,更改/inc/fun_core.php解决 (Issue #15)





 
RT,只能手动更改目录下的config.php文件,网页上保存设置无反应。报错内容如下
 <br /&gt; <b&gt;Warning</b&gt;:  file_put_contents(/www/wwwroot/网页目录../config.php): failed to open stream: No such file or directory in <b&gt;/www/wwwroot/网页目录/inc/fun_core.php</b&gt; on line <b&gt;402</b&gt;<br /&gt; {"errno": 0, "errmsg": "success"}  
看报错发现是config.php目录获取错误，多获取了个根目录的样子？于是去查。
 查看了fun_core.php的402行文件,删掉get_base_root().即可保存,难道是相对目录和绝对目录弄错了？
 不知道是否只有我的环境遇到这个问题，麻烦开发者了。

**Comment by Xiefengshang** [comment]
> 感谢反馈，我记得已经修改过了，后来撤销了推送，导致代码丢失了，小bug无需担心，本项目会长期维护。至于本次反馈的问题，不应该修改fun_core，而是应该写为save_config()，也就是无需参数，会自动正确保存config，而无需手动指定相对位置。 在下个版本更新前，我会把所有功能点全部列出来，每次更新后全部功能点都进行测试，尽可能减少此类情况。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "zhufenghua1998/bp3" ***@***.***&gt;; 发送时间:&nbsp;2022年4月9日(星期六) 晚上8:52 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[zhufenghua1998/bp3] [bug]无法修改config内容,更改/inc/fun_core.php解决 (Issue #15) RT,只能手动更改目录下的config.php文件,网页上保存设置无反应。报错内容如下 <br /&gt; <b&gt;Warning</b&gt;: file_put_contents(/www/wwwroot/网页目录../config.php): failed to open stream: No such file or directory in <b&gt;/www/wwwroot/网页目录/inc/fun_core.php</b&gt; on line <b&gt;402</b&gt;<br /&gt; {"errno": 0, "errmsg": "success"} 看报错发现是config.php目录获取错误，多获取了个根目录的样子？于是去查。 查看了fun_core.php的402行文件,删掉get_base_root().即可保存,难道是相对目录和绝对目录弄错了？ 不知道是否只有我的环境遇到这个问题，麻烦开发者了。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

ok,幸苦了
