### ISSUE TITLE
可考虑对接其他网盘？

### ISSUE THREAD

**Issue by arthurfsy** [zhufenghua1998/bp3#5]
已经正常部署使用，功能正常！感谢开发百度网盘的功能。
另外请问是否能类似另外的项目：Alist那样，扩展其他网盘？
（我目前正在使用的是Alist，使用原因是其前端比较美观+支持网盘比较多，也可以考虑直接对接进入Alist哈哈哈）

**Comment by zhufenghua1998** [comment]
感谢使用与建议。以下回答可以帮助到您：

- 前端页面有能力可以自行优化（或pull requests）
- 扩展其他网盘目前仅考虑官方接口（暂未发现其他官方接口，除oneDrive）
- 关于Alist接入bp3问题，暂时未和Alist开发者有任何联系（我和这些大佬并不熟悉，如果可以感谢引荐）

本人是学生，能力有限，也比较忙，如果Alist考虑接入百度网盘，也许我可以贡献一些思路或代码。
